// flow-typed signature: f07c71874d81a125cb49fc9b495f023f
// flow-typed version: <<STUB>>/vue-loader_v^15.2.6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-loader/lib/codegen/customBlocks' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/codegen/hotReload' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/codegen/styleInjection' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/codegen/utils' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/index' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/loaders/pitcher' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/loaders/stylePostLoader' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/loaders/templateLoader' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/plugin' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/runtime/componentNormalizer' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/select' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-loader/lib/codegen/customBlocks.js' {
  declare module.exports: $Exports<'vue-loader/lib/codegen/customBlocks'>;
}
declare module 'vue-loader/lib/codegen/hotReload.js' {
  declare module.exports: $Exports<'vue-loader/lib/codegen/hotReload'>;
}
declare module 'vue-loader/lib/codegen/styleInjection.js' {
  declare module.exports: $Exports<'vue-loader/lib/codegen/styleInjection'>;
}
declare module 'vue-loader/lib/codegen/utils.js' {
  declare module.exports: $Exports<'vue-loader/lib/codegen/utils'>;
}
declare module 'vue-loader/lib/index.js' {
  declare module.exports: $Exports<'vue-loader/lib/index'>;
}
declare module 'vue-loader/lib/loaders/pitcher.js' {
  declare module.exports: $Exports<'vue-loader/lib/loaders/pitcher'>;
}
declare module 'vue-loader/lib/loaders/stylePostLoader.js' {
  declare module.exports: $Exports<'vue-loader/lib/loaders/stylePostLoader'>;
}
declare module 'vue-loader/lib/loaders/templateLoader.js' {
  declare module.exports: $Exports<'vue-loader/lib/loaders/templateLoader'>;
}
declare module 'vue-loader/lib/plugin.js' {
  declare module.exports: $Exports<'vue-loader/lib/plugin'>;
}
declare module 'vue-loader/lib/runtime/componentNormalizer.js' {
  declare module.exports: $Exports<'vue-loader/lib/runtime/componentNormalizer'>;
}
declare module 'vue-loader/lib/select.js' {
  declare module.exports: $Exports<'vue-loader/lib/select'>;
}
